Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  3.0.516.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Radius Search Extended Parameters' data form
''' </summary>
Partial Public Class [RadiusSearchExtendedParametersUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _addresstype As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.0.516.0")> _
    Public Sub New()
        MyBase.New()

        _addresstype = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/custommapping/RadiusSearchExtendedParameters.html"

        '
        '_addresstype
        '
        _addresstype.Name = "ADDRESSTYPE"
        _addresstype.Caption = "Include only addresses with this type"
        _addresstype.CodeTableName = "ADDRESSTYPECODE"
        Me.Fields.Add(_addresstype)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Include only addresses with this type
    ''' </summary>
    <System.ComponentModel.Description("Include only addresses with this type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.0.516.0")> _
    Public ReadOnly Property [ADDRESSTYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _addresstype
        End Get
    End Property
    
End Class
